@startuml

left to right direction

actor "Socio" as s
actor "Biblioteca" as b

rectangle Biblioteca {
    usecase "Reservar libro" as UC1
    usecase "Prestar libro" as UC2
    usecase "Devolver libro" as UC3
    usecase "Actualizar catálogo" as UC4
}

s -- UC1
s -- UC2
s -- UC3
b -- UC2
b -- UC4

@enduml