@startuml

actor "Agente" as a

usecase "Enviar\nSolicitud de crédito" as UC1
usecase "Enviar\nSolicitud de crédito\npersonal" as UC2
usecase "Enviar\nSolicitud de crédito\nempresarial" as UC3

a -right-> UC1
UC1 <|-- UC2
UC1 <|-- UC3

@enduml