@startuml

left to right direction

actor "Actor" as a
actor "Actor 1" as b

rectangle sistema {
    usecase "caso de uso" as UC1
    usecase "caso de uso" as UC2
    usecase "caso de uso" as UC3
}

a -- UC1
a -- UC2
a -- UC3
b -- UC1
b -- UC3

@enduml